ELearning/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("coursebuilder/", include("coursebuilder.urls")),
    path("admin/", admin.site.urls),
    path("", include("payments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coursebuilder/urls.py
# urls.py

from django.urls import path
from . import views
from .views import * 

urlpatterns = [

  path('', views.home, name='home'),

  # Authentication
  path('login/', views.login_here, name='login_here'),
  path('signup/', views.signup, name='signup'),
  path('logout/', views.logout_here, name='logout_here'),
  path('forgotpassword/', views.forgot_password, name='forgot_password'),

  # Course-related URLs
  path('courses/', views.course_list, name='course_list'),
  path('course/<int:course_id>/', views.course_detail, name='course_detail'),
  path('course/create/', views.course_create, name='course_create'),
  path('course/<int:course_id>/update/', views.course_update, name='course_update'),
  path('course/<int:course_id>/delete/', views.course_delete, name='course_delete'),

  # Assignment-related URLs
  path('course/<int:course_id>/assignments/', views.assignment_list, name='assignment_list'),
  path('course/<int:course_id>/assignment/create/', views.assignment_create, name='assignment_create'),
  path('course/<int:course_id>/assignment/<int:assignment_id>/', views.assignment_detail, name='assignment_detail'),
  path('course/<int:course_id>/assignment/<int:assignment_id>/update/', views.assignment_update, name='assignment_update'),
  path('course/<int:course_id>/assignment/<int:assignment_id>/delete/', views.assignment_delete, name='assignment_delete'),
  path('course/<int:course_id>/assignment/<int:assignment_id>/download/', views.assignment_download, name='assignment_download'),

  #grade
  path('grades/', views.grade_student, name='grade_student'),
  path('gradesprof/', views.grade_professor, name='grade_professor'),

  #aboutus
  path('aboutus/', AboutUsView.as_view(), name='aboutus'),

  #Membership-related URLs
  path('course/<int:course_id>/membership/', views.membership_detail, name='membership_details'),

  # Events-related URLs
  path('events/', views.event_list, name='event_list'),
  path('event/<int:event_id>/', views.event_detail, name='event_detail'),
  path('event/create/', views.event_create, name='event_create'),
  path('event/<int:event_id>/update/', views.event_update, name='event_update'),
  path('event/<int:event_id>/delete/', views.event_delete, name='event_delete'),
]

payments/urls.py
from django.urls import path

from .views import *

app_name = 'payments'

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('detail/<id>/', ProductDetailView.as_view(), name='detail'),
    path('success/', PaymentSuccessView.as_view(), name='success'),
    path('failed/', PaymentFailedView.as_view(), name='failed'),
    path('history/', OrderHistoryListView.as_view(), name='history'),

    path('api/checkout-session/<id>/', create_checkout_session, name='api_checkout_session'),
]

coursebuilder/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core import validators

class UserProfile(User):
  fullname = models.CharField(max_length=30, null=True)
  is_student = models.BooleanField(default=True)
  is_professor = models.BooleanField(default=False)
  MEMBERSHIP_CHOICES = [
    ('Bronze', 'Bronze'),
    ('Silver', 'Silver'),
    ('Gold', 'Gold'),
  ]
  membership = models.CharField(max_length=10, choices=MEMBERSHIP_CHOICES, default='B')
  
  def __str__(self):
    return self.fullname

class Course(models.Model):
  user = models.ManyToManyField(UserProfile)
  title = models.CharField(max_length=200)
  description = models.TextField()
  price = models.FloatField( null=True, blank=True,
        verbose_name='Price',
        validators=[
            validators.MinValueValidator(50),
            validators.MaxValueValidator(100000)
        ]
  )

  def __str__(self):
    return self.title

class Assignment(models.Model):
  course = models.ForeignKey(Course, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  description = models.TextField()
  due_date = models.DateField()
  file = models.FileField(upload_to='assignments/')
  def __str__(self):
    return self.title

class Grade(models.Model):
  course = models.ForeignKey(Course, on_delete=models.CASCADE)
  user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
  assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
  grade = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

  def __str__(self):
    return str(self.grade)
  
class Labs(models.Model):
  course = models.ForeignKey(Course, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  description = models.TextField()
  lab_date = models.DateField()
  file = models.FileField(upload_to='labs/')

  def __str__(self):
    return self.title

class Notes(models.Model):
  course = models.ForeignKey(Course, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  content = models.TextField()

  def __str__(self):
    return self.title

class PPT(models.Model):
  course = models.ForeignKey(Course, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  file = models.FileField(upload_to='ppt_files/')

  def __str__(self):
    return self.title

class CourseEvent(models.Model):
  course = models.ForeignKey(Course, on_delete=models.CASCADE)
  title = models.CharField(max_length=200)
  description = models.TextField()
  start = models.DateTimeField()
  end = models.DateTimeField()

  def __str__(self):
    return self.title

class MembersName(models.Model):
  first_name = models.CharField(max_length=50, null=False)
  last_name = models.CharField(max_length=50, null=False)
  # semester = models.PositiveIntegerField(default=3)
  # link = models.URLField()

  def __str__(self):
    return self.first_name

class Events(models.Model):
  user = models.ManyToManyField(UserProfile)
  title = models.CharField(max_length=200)
  description = models.TextField()
  price = models.FloatField( null=True, blank=True,
        verbose_name='Price',
        validators=[
            validators.MinValueValidator(50),
            validators.MaxValueValidator(100000)
        ]
  )

  def __str__(self):
    return self.title

class Video(models.Model):
  title = models.CharField(max_length=200)
  video_file = models.FileField(upload_to='videos/%y')
  description = models.TextField()

  def __str__(self):
    return self.title

coursebuilder/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import EventForm, CourseForm, AssignmentForm, GradeForm, GradeStudentForm, ForgotPasswordForm, SignUpForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
import pdb
from django.contrib.auth.models import User
from django.db.models import Q
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, DetailView, TemplateView

@login_required
def home(request):
    courses = Course.objects.all()
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.is_professor:
        return render(request, 'home.html', {'courses': courses})
    else:
        return render(request, 'home_student.html', {'courses': courses})

def signup(request):
  if request.method == 'POST':
      form = SignUpForm(request.POST)
      if form.is_valid():
          user = form.save()
          login(request, user)
          return redirect('login_here')
  else:
      form = SignUpForm()
  return render(request, 'signup.html', {'form': form})

def course_list(request):
    courses = Course.objects.all()
    # pdb.set_trace()
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.is_professor:
        return render(request, 'course_list.html', {'courses': courses})
    else:
        return render(request, 'course_list_student.html', {'courses': courses})

def course_detail(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.is_professor:
        return render(request, 'course_detail.html', {'course': course})
    else:
        return render(request, 'course_detail_student.html', {'course': course, 'user': user})

def course_create(request):
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            course = form.save()
            return redirect('course_detail', course_id=course.id)
    else:
        form = CourseForm()
    return render(request, 'course_form.html', {'form': form})

def course_update(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('course_detail', course_id=course.id)
    else:
        form = CourseForm(instance=course)
    return render(request, 'course_form.html', {'form': form, 'course': course})

def course_delete(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        course.delete()
        return redirect('course_list')
    return render(request, 'course_confirm_delete.html', {'course': course})

def assignment_delete(request, course_id, assignment_id):
    course = get_object_or_404(Course, id=course_id)
    courseid = course_id
    assignment = get_object_or_404(Assignment, id=assignment_id)
    if request.method == 'POST':
        assignment.delete()
        return redirect('assignment_list', course_id=courseid)
    return render(request, 'course_confirm_delete.html', {'assignment': assignment})

def assignment_detail(request, course_id, assignment_id):
    course = get_object_or_404(Course, id=course_id)
    assignment = get_object_or_404(Assignment, id=assignment_id)
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.is_professor:
        return render(request, 'assignment_detail.html', {'assignment': assignment})
    else:
        return render(request, 'assignment_detail_student.html', {'assignment': assignment})

def assignment_list(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    assignments = Assignment.objects.filter(course=course)
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.is_professor:
        return render(request, 'assignment_list.html', {'course': course, 'assignments': assignments})
    else:
        return render(request, 'assignment_list_student.html', {'course': course, 'assignments': assignments})
        
def assignment_create(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        form = AssignmentForm(request.POST, request.FILES)
        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.course = course
            assignment.save()
            return redirect('assignment_list', course_id=course.id)
    else:
        form = AssignmentForm()
    return render(request, 'assignment_form.html', {'form': form, 'course': course})

def assignment_download(request, course_id, assignment_id):
    course = Course.objects.get(id=course_id)
    assignment = Assignment.objects.get(id=assignment_id)
    response = FileResponse(assignment.file)
    response['Content-Disposition'] = f'attachment; filename="{assignment.file.name}"'
    return response

def assignment_update(request, course_id, assignment_id):
    course = get_object_or_404(Course, id=course_id)
    assignment = get_object_or_404(Assignment, id=assignment_id)
    if request.method == 'POST':
        form = AssignmentForm(request.POST, instance=assignment)
        if form.is_valid():
            form.save()
            return redirect('assignment_detail', course_id=course.id, assignment_id=assignment.id)
    else:
        form = CourseForm(instance=course)
    return render(request, 'assignment_form.html', {'form': form, 'assignment': assignment})


def login_here(request):
  if request.method == 'POST':
    username = request.POST.get('username')
    password = request.POST.get('password') 
    user = authenticate(request, username=username, password=password)
    # pdb.set_trace()
    if user is not None:
      if user.is_active:
        login(request, user)
        return HttpResponseRedirect(reverse('home'))
      else:
        return HttpResponse('Your account is disabled')
    else:
      return HttpResponse('Login details are incorrect')
  else:
    return render(request, 'login_here.html')

@login_required
def logout_here(request):
  logout(request)
  return HttpResponseRedirect(reverse(('home')))


def forgot_password(request):
  if request.method == 'POST':
    form = ForgotPasswordForm(request.POST)
    if form.is_valid():
      # order = form.save(commit=False)
      # pdb.set_trace()
      password = form.cleaned_data['password']
      username = form.cleaned_data['username']
      u = User.objects.get(username=username)
      u.set_password(password)
      u.save()
      return render(request, 'login_here.html')
  else:
    form = ForgotPasswordForm()
  return render(request, 'forgot_password.html', {'form': form})

def grade_student(request):
    # pdb.set_trace()
    if request.method == 'POST':
        form = GradeStudentForm(request.POST)
        if form.is_valid():
            selected_course = form.cleaned_data['course']
            selected_assignment = form.cleaned_data['assignment']
            user = UserProfile.objects.get(user_ptr=request.user.id)
            grade = Grade.objects.get(Q(course=selected_course) & Q(assignment=selected_assignment) & Q(user=user))
        return render(request, 'grade_student.html', {'form': form, 'grade': grade})
    else:
        form = GradeStudentForm()
    return render(request, 'grade_student.html', {'form': form})

def grade_professor(request):
  if request.method == 'POST':
    form = GradeForm(request.POST)
    if form.is_valid():
      grade = form.save()
      return render(request, 'grade_success.html')
    else:
        return render(request, 'grade_nosuccess.html')
  else:
    form = GradeForm()
  return render(request, 'grade_professor.html', {'form': form})

class AboutUsView(View):

  def get(self, request):
    team_members = MembersName.objects.all()
    return render(request, 'aboutus.html', {'team_members': team_members})

def membership_detail(request, course_id):
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.membership == 'Gold':
        video = Video.objects.all()
        return render(request, 'membership.html', {'video': video, 'user': user})
    elif user.membership == 'Silver':
        video = Video.objects.all()[:2]
        return render(request, 'membership.html', {'video': video, 'user': user})
    
def event_list(request):
    events = Events.objects.all()
    # pdb.set_trace()
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.is_professor:
        return render(request, 'event_list.html', {'events': events})
    else:
        return render(request, 'event_list_student.html', {'events': events})

def event_detail(request, event_id):
    event = get_object_or_404(Events, id=event_id)
    user = UserProfile.objects.get(user_ptr=request.user.id)
    if user.is_professor:
        return render(request, 'event_detail.html', {'event': event})
    else:
        return render(request, 'event_detail_student.html', {'event': event, 'user': user})

def event_create(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save()
            return redirect('event_detail', event_id=event.id)
    else:
        form = EventForm()
    return render(request, 'event_form.html', {'form': form})

def event_update(request, event_id):
    event = get_object_or_404(Events, id=event_id)
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('event_detail', event_id=event.id)
    else:
        form = EventForm(instance=event)

coursebuilder/templates/assignment_detail.html
<!-- course_detail.html -->
{% extends 'base.html' %}

{% block title %}{{ assignment.title }} - Assignment Detail{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">{{ assignment.title }}</h1>
            </div>
            <div class="card-body">
                <!-- <p class="card-text">{{ course.description }}</p> -->
                <!-- Add other course details here if needed -->
                <p class="card-text">Description: {{ assignment.description }}</p>
                <p class="card-text">Due Date: {{ assignment.due_date }}</p>
                <p class="card-text">File: {{ assignment.file }}</p>
                <!-- <p class="card-text">Grade: {{ assignment.grade }}</p> -->
                <a href="{% url 'assignment_download' assignment.course.id assignment.id %}">Download File</a>
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center">
                <a href="{% url 'assignment_list' assignment.course.id %}" class="btn btn-secondary">Assignment List</a>
                <a href="{% url 'assignment_update' assignment.course.id assignment.id %}" class="btn btn-primary">Edit Assignment</a>
              </div>
        </div>
    </div>
{% endblock %}

coursebuilder/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Course Builder{% endblock %}</title>
  <!-- Add the Bootstrap CSS link -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <!-- Navigation bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">CourseBuilder</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'course_list' %}">Courses</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Grades</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'event_list' %}">Events</a>
              </li>
            </ul>
      </div>
  </nav>

  <!-- Content block -->
  <div class="content">
    <br>
    {% block content %}
    {% endblock %}
  </div>
  <div class="fixed-bottom text-center bg-primary">
    <a href="{% url 'aboutus' %}" style="color: white;font-size: 20px;">About Us</a>   
  </div>
  <!-- Add the Bootstrap JavaScript link -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

coursebuilder/templates/course_detail.html
<!-- course_detail.html -->
{% extends 'base.html' %}

{% block title %}{{ course.title }} - Course Detail{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">{{ course.title }}</h1>
                <a href="#" class="btn btn-secondary">Attendance</a>
                <a href="#" class="btn btn-secondary">Grades</a>
                <a href="{% url 'assignment_list' course.id %}" class="btn btn-secondary">Assignments</a>
            </div>
            <div class="card-body">
                <p class="card-text">{{ course.description }}</p>
                <!-- Add other course details here if needed -->
                
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center">
                <a href="{% url 'course_list' %}" class="btn btn-secondary">Course List</a>
                <a href="{% url 'course_update' course.id %}" class="btn btn-primary">Edit Course</a> 
            </div>
        </div>
    </div>
{% endblock %}

coursebuilder/templates/course_detail_student.html
<!-- course_detail.html -->
{% extends 'base.html' %}

{% block title %}{{ course.title }} - Course Detail{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="card">
            <div class="card-header">
                <h1 class="card-title">{{ course.title }}</h1>
                <a href="{% url 'grade_student' %}" class="btn btn-secondary">Grades</a>
                <a href="{% url 'assignment_list' course.id %}" class="btn btn-secondary">Assignments</a>
                {% if user.membership != 'Bronze' %}
                    <a href="{% url 'membership_details' course.id %}" class="btn btn-secondary"> {{ user.membership }}</a>
                {% else %}
                    <a href="" class="btn btn-secondary"> {{ user.membership }}</a>
                {% endif %}
            </div>
            <div class="card-body">
                <p class="card-text">{{ course.description }}</p>
                <!-- Add other course details here if needed -->
                
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center">
                <a href="{% url 'course_list' %}" class="btn btn-secondary">Course List</a>
            </div>
        </div>
    </div>
{% endblock %}

coursebuilder/templates/course_form.html
{% extends 'base.html' %}

{% block title %}{% if course %}Edit {% else %}Create New {% endif %} Course{% endblock %}

{% block content %}
    <div class="container">
        <h1>{% if course %}Edit {% else %}Create New {% endif %} Course</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title:</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_description">Description:</label>
                {{ form.description }}
            </div>
            {# Add more form fields here if needed #}
            <button type="submit" class="btn btn-primary">
                {% if course %}Update {% else %}Create {% endif %} Course
            </button>
            <a href="{% url 'course_list' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

coursebuilder/templates/course_list.html
<!-- course_list.html -->
{% extends 'base.html' %}

{% block title %}Course List{% endblock %}

{% block content %}
    <div class="container">
        <h1>Course List</h1>
        <ul class="list-group">
            {% for course in courses %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'course_detail' course.id %}">{{ course.title }}</a>
                        <div class="btn-group">
                            <a href="{% url 'course_update' course.id %}" class="btn btn-sm btn-primary">Edit</a>
                            <a href="{% url 'course_delete' course.id %}" class="btn btn-sm btn-danger">Delete</a>
                        </div>
                </li>
            {% endfor %}
        </ul>
        
        <a href="{% url 'course_create' %}" class="btn btn-primary mt-3">Create New Course</a>
    </div>
{% endblock %}

coursebuilder/templates/course_list_student.html
<!-- course_list.html -->
{% extends 'base.html' %}

{% block title %}Course List{% endblock %}

{% block content %}
    <div class="container">
        <h1>Course List</h1>
        <ul class="list-group">
            {% for course in courses %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'course_detail' course.id %}">{{ course.title }}</a>
                    
                </li>
            {% endfor %}
        </ul>
        
    </div>
    
{% endblock %}

coursebuilder/templates/home_student.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <!-- Include Bootstrap CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Include custom CSS for dashboard styling -->
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}" />
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">CourseBuilder</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'course_list' %}">Courses</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'grade_student' %}">Grades</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'event_list' %}">Events</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'payments:home' %}">Buy Courses</a>
                  </li>   
                </ul>
        </div>
    </nav>
    

    <div class="container">
        <div class="row">

            <!-- Main Content Area -->
            <main class="col">
                <div class="my-4">
                    <h2>Welcome!!</h2>
                    <!-- <p>Here, you can access your courses and assignments.</p> -->
                </div>

                <!-- List of Courses as Cards -->
                <div class="row">
                    {% for course in courses %}
                        <div class="col-md-4 mb-4">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">{{ course.title }}</h5>
                                    <p class="card-text">{{ course.description }}</p>
                                    <a href="{% url 'course_detail' course.id %}" class="btn btn-primary">View Course</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <!-- Add more course cards here -->
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle w-100" type="button" id="courseDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Progress
                            </button>
                            <div class="dropdown-menu w-100" aria-labelledby="courseDropdown">
                                {% for course in courses %}
                                    <div class="dropdown-item">
                                        <h6>{{ course.title }}</h6>
                                        <div class="progress">
                                            <div class="progress-bar" role="progressbar" style="width: 10%;" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">10%</div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="card mb-4">
                            <div class="card-header l-bg-blue-dark">
                                <b><span style="color:black;">Growth</span>
                            </div>
                            <div class="card-body"><canvas id="myAreaChart" width="100%" height="50"></canvas></div>
                        </div>
                      </div>
                </div>
            </main>

        </div>
    </div>
    <div class="text-center bg-primary">
        <a href="{% url 'aboutus' %}" style="color: white; font-size: 20px; text-decoration: none!important;">About Us</a>    
    </div>
    <!-- Include Bootstrap JS (Optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        // Set new default font family and font color to mimic Bootstrap's default styling
        Chart.defaults.global.defaultFontFamily = '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
        Chart.defaults.global.defaultFontColor = '#292b2c';
      
      
        // Area Chart
        var ctx = document.getElementById("myAreaChart");
        var myLineChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: ["June 1", "June 10", "June 20", "June 30", "July 1", "July 5", "July 10", "July 15", "July 20"],
            datasets: [{
              label: "Sessions",
              lineTension: 0.3,
              backgroundColor: "rgba(2,117,216,0.2)",
              borderColor: "rgba(2,117,216,1)",
              pointRadius: 5,
              pointBackgroundColor: "rgba(2,117,216,1)",
              pointBorderColor: "rgba(255,255,255,0.8)",
              pointHoverRadius: 5,
              pointHoverBackgroundColor: "rgba(2,117,216,1)",
              pointHitRadius: 50,
              pointBorderWidth: 2,
              data: [0, 10, 20, 20, 35, 28, 40, 50, 60, 45, 70, 80, 100],
            }],
          },
          options: {
            scales: {
              xAxes: [{
                time: {
                  unit: 'date'
                },
                gridLines: {
                  display: false
                },
                ticks: {
                  maxTicksLimit: 7
                }
              }],
              yAxes: [{
                ticks: {
                  min: 0,
                  max: 100,
                  maxTicksLimit: 5
                },
                gridLines: {
                  color: "rgba(0, 0, 0, .125)",
                }
              }],
            },
            legend: {
              display: false
            }
          }
        });
      </script>
</body>
</html>