ELearning/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("coursebuilder/", include("coursebuilder.urls")),
    path("admin/", admin.site.urls),
    path("", include("payments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path

from .views import *

app_name = 'payments'

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('detail/<id>/', ProductDetailView.as_view(), name='detail'),
    path('success/', PaymentSuccessView.as_view(), name='success'),
    path('failed/', PaymentFailedView.as_view(), name='failed'),
    path('history/', OrderHistoryListView.as_view(), name='history'),

    path('api/checkout-session/<id>/', create_checkout_session, name='api_checkout_session'),
]

payments/models.py
from django.core import validators
from django.db import models


# Create your models here.
class Product(models.Model):
    id = models.BigAutoField(
        primary_key=True
    )

    name = models.CharField(
        max_length=70,
        verbose_name='Product Name'
    )

    description = models.TextField(
        max_length=800,
        verbose_name='Description'
    )

    price = models.FloatField(
        verbose_name='Price',
        validators=[
            validators.MinValueValidator(50),
            validators.MaxValueValidator(100000)
        ]
    )


class OrderDetail(models.Model):
    id = models.BigAutoField(
        primary_key=True
    )

    # You can change as a Foreign Key to the user model
    customer_email = models.EmailField(
        verbose_name='Customer Email'
    )

    product = models.ForeignKey(
        to=Product,
        verbose_name='Product',
        on_delete=models.PROTECT
    )

    amount = models.IntegerField(
        verbose_name='Amount'
    )

    stripe_payment_intent = models.CharField(
        max_length=200, null=True, blank=True
    )

    # This field can be changed as status
    has_paid = models.BooleanField(
        default=False,
        verbose_name='Payment Status'
    )

    created_on = models.DateTimeField(
        auto_now_add=True
    )

    updated_on = models.DateTimeField(
        auto_now_add=True
    )

payments/views.py
import json

import stripe
from django.conf import settings
from django.http.response import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, DetailView, TemplateView

from .models import *


# Create your views here.

class ProductListView(ListView):
    model = Product
    template_name = "payments/product_list.html"
    context_object_name = 'product_list'


class ProductCreateView(CreateView):
    model = Product
    fields = '__all__'
    template_name = "payments/product_create.html"
    success_url = reverse_lazy("home")


class ProductDetailView(DetailView):
    model = Product
    template_name = "payments/product_detail.html"
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['stripe_publishable_key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


@csrf_exempt
def create_checkout_session(request, id):
    request_data = json.loads(request.body)
    product = get_object_or_404(Product, pk=id)

    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        # Customer Email is optional,
        # It is not safe to accept email directly from the client side
        customer_email=request_data['email'],
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'inr',
                    'product_data': {
                        'name': product.name,
                    },
                    'unit_amount': int(product.price * 100),
                },
                'quantity': 1,
            }
        ],
        mode='payment',
        success_url=request.build_absolute_uri(
            reverse('payments:success')
        ) + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse('payments:failed')),
    )

    # OrderDetail.objects.create(
    #     customer_email=email,
    #     product=product, ......
    # )

    order = OrderDetail()
    order.customer_email = request_data['email']
    order.product = product
    order.stripe_payment_intent = checkout_session['payment_intent']
    order.amount = int(product.price * 100)
    order.save()

    # return JsonResponse({'data': checkout_session})
    return JsonResponse({'sessionId': checkout_session.id})


class PaymentSuccessView(TemplateView):
    template_name = "payments/payment_success.html"

    def get(self, request, *args, **kwargs):
        session_id = request.GET.get('session_id')
        if session_id is None:
            return HttpResponseNotFound()

        stripe.api_key = settings.STRIPE_SECRET_KEY
        session = stripe.checkout.Session.retrieve(session_id)

        order = get_object_or_404(OrderDetail, stripe_payment_intent=session.payment_intent)
        order.has_paid = True
        order.save()
        return render(request, self.template_name)


class PaymentFailedView(TemplateView):
    template_name = "payments/payment_failed.html"


class OrderHistoryListView(ListView):
    model = OrderDetail
    template_name = "payments/order_history.html"

payments/templates/payments/base.html
<!doctype html>
<html lang="en">

<head>
    <title>Django Payments App</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
{% include 'payments/navbar.html' %}

{% block content %}

{% endblock content %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
</body>

</html>

payments/templates/payments/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-primary">
    <a class="navbar-brand" href="#">CourseBuilder</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'payments:home' %}">Home</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

payments/templates/payments/order_history.html
{% extends 'payments/base.html' %}

{% block content %}
    <h1 class="text-center">Order History</h1>
    <div class="container">

        {% if object_list %}
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>Product</th>
                    <th>Customer Email</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>

                {% for i in object_list %}
                    <tr>
                        <td>{{ i.product.name }}</td>
                        <td>{{ i.customer_email }}</td>
                        <td>{{ i.amount }}</td>
                        <td>
                            {% if i.has_paid %}
                                <b class="text-success">Success</b>
                            {% else %}
                                <b class="text-danger">Failed</b>
                            {% endif %}
                        </td>
                        <td>{{ i.created_on }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info">
                Payment history is empty.
            </div>
        {% endif %}

    </div>
{% endblock content %}
    

payments/templates/payments/payment_failed.html
{% extends 'payments/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center mt-5">
            <h1 class="text-danger">Payment Failed</h1>
            <p>We received your order. You can now close this window or use the
                link below to visit
                <a href="{% url 'home' %}">home page</a>.
            </p>
        </div>
    </div>
{% endblock content %}

payments/templates/payments/payment_success.html
{% extends 'payments/base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron text-center mt-5">
            <h1 class="text-success">Payment Success</h1>
            <p>We received your order. You can now close this window or use the
                link below to visit
                <a href="{% url 'home' %}">home page</a>.
            </p>
        </div>
    </div>
{% endblock content %}

payments/templates/payments/product_create.html
{% extends 'payments/base.html' %}

{% block content %}
    <h1 class="text-center">Create Product</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                <form method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        document.querySelectorAll('input, textarea').forEach(e => {
            e.classList.add('form-control');
        })
    </script>
{% endblock content %}

payments/templates/payments/product_detail.html
{% extends 'payments/base.html' %}

{% block content %}
    <h1 class="text-center">Product Detail</h1>
    <div class="container">

        <div class="card">
            <div class="card-header">
                <h2>Course Detail</h2>
            </div>
            <div class="card-body">
                <div class="container row">
                    <div class="col-md-2">
                        <img src="https://dummyimage.com/150x150.gif?text={{ object.name }}" alt="">
                    </div>
                    <div class="col-md-10">
                        <h1>Name: {{ object.name }}</h1>
                        <p>Description: {{ object.description }}</p>
                        <p>Price: {{ object.price }}</p>

                        <div class="form-group">
                            <label for="email">Email: </label>
                            <input type="email" name="email" id="email" class="form-control" placeholder="Email">
                            <small>Please enter your email address</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer d-flex">
                <button class="btn btn-success ml-auto" id="checkout-button">Checkout</button>
            </div>
        </div>
    </div>

    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        // Create an instance of the Stripe object with your publishable API key
        var stripe = Stripe('{{ stripe_publishable_key }}');
        var checkoutButton = document.getElementById('checkout-button');

        checkoutButton.addEventListener('click', function () {

            var email = document.getElementById('email').value;
            if (email.length == 0) {
                alert("Please enter your email address.");
                return;
            }

            // Create a new Checkout Session using the server-side endpoint you
            // created in step 3.
            fetch("{% url 'payments:api_checkout_session' id=object.id %}", {
                method: 'POST',
                body: JSON.stringify(
                    {email: email}
                )
            })
                .then(function (response) {
                    return response.json();
                })
                .then(function (session) {
                    return stripe.redirectToCheckout({sessionId: session.sessionId});
                })
                .then(function (result) {
                    // If `redirectToCheckout` fails due to a browser or network
                    // error, you should display the localized error message to your
                    // customer using `error.message`.
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function (error) {
                    console.error('Error:', error);
                });
        });
    </script>
{% endblock content %}

payments/templates/payments/product_list.html
{% extends 'payments/base.html' %}

{% block content %}
    <h1 class="text-center">Course List</h1>
    <div class="container">
        {% if product_list %}
            <div class="row">


                {% for p in product_list %}
                    <div class="col-sm-4">
                        <div class="card">
                            <img class="card-img-top" src="https://dummyimage.com/200x150.jpg?text={{ p.name }}" alt="">
                            <div class="card-body">
                                <h4 class="card-title">{{ p.name }}</h4>
                                <p class="card-text">{{ p.description }}</p>
                            </div>
                            <div class="card-footer d-flex">
                                <a href="{% url 'payments:detail' id=p.id %}" class="btn btn-success ml-auto">Buy Now</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        {% else %}
            <div class="alert alert-info text-center mt-5">
                The product list is empty. Please add some products first.
            </div>
        {% endif %}
    </div>
{% endblock content %}